### ISSUE TITLE
Крэш при выходе по back

### ISSUE THREAD

**Issue by zagayevskiy** [artemohanjanyan/CPClient#1]
Process: pack.cpclient, PID: 26120
                                                               java.lang.RuntimeException: Unable to destroy activity {pack.cpclient/pack.cpclient.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
                                                                   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4208)
                                                                   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226)
                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:177)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1503)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
                                                                   at pack.cpclient.fragments.ViewPagerFragment.detachProvider(ViewPagerFragment.java:82)
                                                                   at pack.cpclient.activity.MainActivity.onLoaderReset(MainActivity.java:109)
                                                                   at android.support.v4.app.LoaderManagerImpl$LoaderInfo.destroy(LoaderManager.java:357)
                                                                   at android.support.v4.app.LoaderManagerImpl.doDestroy(LoaderManager.java:827)
                                                                   at android.support.v4.app.FragmentHostCallback.doLoaderDestroy(FragmentHostCallback.java:268)
                                                                   at android.support.v4.app.FragmentController.doLoaderDestroy(FragmentController.java:371)
                                                                   at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:369)
                                                                   at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:203)
                                                                   at android.app.Activity.performDestroy(Activity.java:6525)
                                                                   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
                                                                   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4186)
                                                                   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226) 
                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:177) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1503) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:145) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by artemohanjanyan** [comment]
fixed
